DROP TABLE IF EXISTS FILES_GENERATED;
 
CREATE TABLE FILES_GENERATED (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FILE_NAME VARCHAR(1000) NOT NULL,
  CONTENT VARCHAR(5000) NOT NULL,
  DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
 
INSERT INTO FILES_GENERATED (FILE_NAME, CONTENT) VALUES
  ('FILE_01.txt', 'Content File 01 generated'),
  ('FILE_02.txt', 'Content File 02 generated'),
  ('FILE_03.txt', 'Content File 03 generated')
