DROP TABLE IF EXISTS FILES_GENERATED;
DROP TABLE IF EXISTS CSV_CONTENT;
 
CREATE TABLE FILES_GENERATED (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CSV_FILE_NAME VARCHAR(1000) NOT NULL,
  FILE_NAME VARCHAR(1000) NOT NULL,
  CONTENT VARCHAR(5000) NOT NULL,
  DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CSV_CONTENT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CSV_FILE_NAME VARCHAR(1000),
  COLUMN1 VARCHAR(1000),
  COLUMN2 VARCHAR(1000),
  COLUMN3 VARCHAR(1000),
  COLUMN4 VARCHAR(1000),
  COLUMN5 VARCHAR(1000),
  COLUMN6 VARCHAR(1000),
  COLUMN7 VARCHAR(1000),
  COLUMN8 VARCHAR(1000)
);